stages:
  - build
  - deploy


image: node

build:
  stage: build
  cache:
    key:
      files:
        - package-lock.json
      prefix: npm
    paths:
      - node_modules/
  artifacts:
    paths:
      - "build/"
  script:
    - npm i
    - npm run clear
    - npm run build
  rules:
    - if: $CI_COMMIT_BRANCH != "main"

# ! DO NOT CHANGE NAME OF THIS.
# ! Used to be 'deploy', and GitLab did not like that.
pages:
  stage: deploy
  cache:
    key:
      files:
        - package-lock.json
      prefix: npm
    paths:
      - node_modules/
  script:
    - npm i
    - npm run clear
    - npm run build
  artifacts:
    paths:
      - build
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
