stages:
  - quality-check
  - build
  - deploy

image: node:16.5.0

quality-check-job:
  script:
    - echo "RUNNING QUALITY CONTROL..."
    - npm install
    - npm run lint

build-job:
  stage: build
  cache:
    key:
      files:
        - package-lock.json
      prefix: npm
    paths:
      - node_modules/
  script:
    - echo "RUNNING BUILD..."
    - npm run build
    - rm -fr public/
    - cp -a dist/. public/
    - cp -fa public/public/* public/
    - rm -fr public/public

pages:
  stage: deploy
  script:
    - echo "DEPLOYING..."
  artifacts:
    paths:
      - public
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH