stages:
  - quality-check
  - build
  - deploy


image: node:16.5.0


quality-check:
  stage: quality-check
  script:
    - echo "RUNNING QUALITY CONTROL..."
    - npm i
    - npm run lint

build:
  stage: build
  cache:
    key:
      files:
        - package-lock.json
      prefix: npm
    paths:
      - node_modules/
  script:
    - echo "RUNNING BUILD..."
    - npm i
    - npm run build
    - rm -fr public/
    - cp -a dist/. public/
    - cp -fa public/public/* public/
    - rm -fr public/public

deploy:
  stage: deploy
  script:
    - echo "DEPLOYING..."
  needs: [build]
  artifacts:
    paths:
      - public
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
